kind: Deployment
apiVersion: apps/v1
metadata:
   name: giri
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: giri
   template:
      metadata:
        labels:
          app: giri
      spec:
       containers:
        - name: giri
          image: giriraj171/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
