kind: Service                             
apiVersion: v1
metadata:
  name: giri
  labels:
    app: giri

spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: giri                    
  type: LoadBalancer
